YELP_YWSID = 'o7f0BvjY65VTw_IQHuJkhA'

YELP_V2_KEYS = {
  :consumer_key => 'EPuiJ7Q6CZpLuL5m8y2anA',
  :consumer_secret => 'Z6YQ5O66VR1bdFsStJ7oRvrv8N8',
  :token => 'w8cASHycaPCBEmOee_KoAUsbE7mx8GZZ',
  :token_secret => '5_zTuD8BeywHvqAsCf4ZMo_ZH7k'
}

YELP_RESTAURANT_CATEGORIES = [
  ["Afghan", "afghani"],
  ["African", "african"],
  ["American (New)", "newamerican"],
  ["American (Traditional)", "tradamerican"],
  ["Argentine", "argentine"],
  ["Asian Fusion", "asianfusion"],
  ["Barbeque", "bbq"],
  ["Basque", "basque"],
  ["Belgian", "belgian"],
  ["Brasseries", "brasseries"],
  ["Brazilian", "brazilian"],
  ["Breakfast & Brunch", "breakfast_brunch"],
  ["British", "british"],
  ["Buffets", "buffets"],
  ["Burgers", "burgers"],
  ["Burmese", "burmese"],
  ["Cafes", "cafes"],
  ["Cajun/Creole", "cajun"],
  ["Cambodian", "cambodian"],
  ["Caribbean", "caribbean"],
  ["Cheesesteaks", "cheesesteaks"],
  ["Chicken Wings", "chicken_wings"],
  ["Chinese", "chinese"],
  ["Chinese - Dim Sum", "dimsum"],
  ["Chinese - Szechuan", "szechuan"],
  ["Creperies", "creperies"],
  ["Cuban", "cuban"],
  ["Delis", "delis"],
  ["Diners", "diners"],
  ["Ethiopian", "ethiopian"],
  ["Fast Food", "hotdogs"],
  ["Filipino", "filipino"],
  ["Fish & Chips", "fishnchips"],
  ["Fondue", "fondue"],
  ["Food Stands", "foodstands"],
  ["French", "french"],
  ["Gastropubs", "gastropubs"],
  ["German", "german"],
  ["Gluten-Free", "gluten_free"],
  ["Greek", "greek"],
  ["Halal", "halal"],
  ["Hawaiian", "hawaiian"],
  ["Himalayan/Nepalese", "himalayan"],
  ["Hot Dogs", "hotdog"],
  ["Hungarian", "hungarian"],
  ["Indian", "indpak"],
  ["Indonesian", "indonesian"],
  ["Irish", "irish"],
  ["Italian", "italian"],
  ["Japanese", "japanese"],
  ["Korean", "korean"],
  ["Kosher", "kosher"],
  ["Latin American", "latin"],
  ["Live/Raw Food", "raw_food"],
  ["Malaysian", "malaysian"],
  ["Mediterranean", "mediterranean"],
  ["Mexican", "mexican"],
  ["Middle Eastern", "mideastern"],
  ["Modern European", "modern_european"],
  ["Mongolian", "mongolian"],
  ["Moroccan", "moroccan"],
  ["Pakistani", "pakistani"],
  ["Persian/Iranian", "persian"],
  ["Peruvian", "peruvian"],
  ["Pizza", "pizza"],
  ["Polish", "polish"],
  ["Portuguese", "portuguese"],
  ["Russian", "russian"],
  ["Salad", "salad"],
  ["Sandwiches", "sandwiches"],
  ["Scandinavian", "scandinavian"],
  ["Seafood", "seafood"],
  ["Singaporean", "singaporean"],
  ["Soul Food", "soulfood"],
  ["Soup", "soup"],
  ["Southern", "southern"],
  ["Spanish", "spanish"],
  ["Steakhouses", "steak"],
  ["Sushi Bars", "sushi"],
  ["Taiwanese", "taiwanese"],
  ["Tapas Bars", "tapas"],
  ["Tapas/Small Plates", "tapasmallplates"],
  ["Tex-Mex", "tex-mex"],
  ["Thai", "thai"],
  ["Turkish", "turkish"],
  ["Ukrainian", "ukrainian"],
  ["Vegan", "vegan"],
  ["Vegetarian", "vegetarian"],
  ["Vietnamese", "vietnamese"]
]